import type { Metadata } from "next";
import "@/sass/index.scss";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased app-layout`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
